name: Auto update

env:
  BUILDER_TOOLS_URL: https://github.com/gasinvein/flatpak-builder-tools.git
  BUILDER_TOOLS_BRANCH: cargo-git-http

on:
  schedule:
    - cron: '0 0 * * 1,5'
  workflow_dispatch: {}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          set -e
          sudo apt update
          sudo apt upgrade -y
          sudo apt install python3-toml python3-aiohttp

      - uses: actions/checkout@v2

      - name: Download flatpak-builder-tools
        run: |
          git clone -b ${BUILDER_TOOLS_BRANCH} \
                       ${BUILDER_TOOLS_URL} \
                       builder-tools

      - name: Run update
        run: |
          set -e
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name "Workflow trigger"
          ./update.py veloren-git.json -g builder-tools/cargo/flatpak-cargo-generator.py --generator-arg=-t
          git push https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}
